version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    restart: "no"
    ports:
      - '3030:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - influxdb
    
  influxdb:
    restart: "no"
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - influxdb

networks:
  influxdb:

volumes:
  influxdb_data: